spring.application.name=aether_backend
# Specifica che useremo SQLite e il nome del file sarà "aether_data.db"
spring.datasource.url=jdbc:sqlite:aether_data.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Permette a Spring di creare/aggiornare le tabelle automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Mostra le query SQL nel terminale (comodo per vedere cosa succede)
spring.jpa.show-sql=true